name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  # 可手动执行
  workflow_dispatch:

env:
  TZ: Asia/Shanghai # 设置时区：中国上海

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 18.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
